spring.application.name=restendpoints
server.error.include-message=always
spring.datasource.url=jdbc:h2:./datenbank:AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=passwor
spring.sql.init.mode=always